// Created by Crowbar 0.68

// Stored modelname (without quotes): "tf1/models/Napalm.mdl"
$ModelName "napalm.mdl"
$CD "."
$CDTexture "."
$ClipToTextures
$Scale 1.0

$BodyGroup "studio"
{
	studio "Napalm_Template1"
}

$Flags 0


// Clipping box or view bounding box.
$CBox 0 0 0 0 0 0

// Bounding box or hull. Used for collision with a world object.
$BBox 0 0 0 0 0 0

$HBox 0 "Napalm01" 0 0 -7.19 82.709999 24.709999 7.39

$Sequence "idle" {
	"napalm_anims\idle"
	fps 10
	loop
}
