// Created by Crowbar 0.68

// Stored modelname (without quotes): "valve/models/presentsm.mdl"
$ModelName "presentsm.mdl"
$CD "."
$CDTexture "."
$ClipToTextures
$Scale 1.0

$BodyGroup "studio"
{
	studio "presentsm_small_reference"
}

$Flags 0


// Clipping box or view bounding box.
$CBox 0 0 0 0 0 0

// Bounding box or hull. Used for collision with a world object.
$BBox 0 0 0 0 0 0

$HBox 0 "Box01" -12.33 -12.81 0 12.33 12.81 26.73

$Sequence "idle" {
	"presentsm_anims\idle"
	fps 30
}
