// Created by Crowbar 0.68

// Stored modelname (without quotes): "tfc/models/p_nailgun.mdl"
$ModelName "p_nailgun2.mdl"
$CD "."
$CDTexture "."
$ClipToTextures
$Scale 1.0

$BodyGroup "body"
{
	studio "p_nailgun2_p_nailgun"
}

$Flags 0


// Clipping box or view bounding box.
$CBox 0 0 0 0 0 0

// Bounding box or hull. Used for collision with a world object.
$BBox 0 0 0 0 0 0

$HBox 0 "Line02" -8.32 -3.65 -1.17 14.23 3.69 8.48

$Sequence "standthere" {
	"p_nailgun2_anims\standthere"
	fps 30
}
